version: '3'

services:
  
  sample:
    container_name: fmk_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always